import type { Decision } from './decide.js';

const esc = (s: unknown) => String(s ?? '').replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]!));
const R = (n: number) => 'R\u00a0' + Math.round(n).toLocaleString('en-ZA');
const pct = (n: number) => (n * 100).toFixed(1) + '%';
const card = (eye: string, h: string, body: string) => `<section><div class="eye">${eye}</div><h2>${h}</h2>${body}</section>`;
const tile = (l: string, v: string, s = '') => `<div class="tile"><div class="eye">${l}</div><div class="v">${v}</div>${s ? `<p>${s}</p>` : ''}</div>`;
const tiles = (a: string[]) => `<div class="tiles">${a.join('')}</div>`;
const na = (v: unknown, f: (x: any) => string) => (v ? f(v) : '<span class="miss">Not found</span>');
const src: Record<string, string> = { jsonld: 'from listing', text: 'from listing', llm: 'read by AI from listing', user: 'you supplied' };

export function renderReport(d: Decision): string {
  const { L, p, bench: b } = d;
  const tone = d.status === 'Affordability stretch' ? 'bad' : d.status === 'Priced in line' || d.status === 'Priced below benchmark' ? 'good' : 'warn';
  const rentLine = p.monthlyRent
    ? `<p>You entered rent of ${R(p.monthlyRent)}. That is ${p.monthlyRent >= d.ownCost ? 'above' : 'below'} the ${R(d.ownCost)} it costs to own before principal, so ${p.monthlyRent >= d.ownCost ? 'owning costs less than renting a similar place' : 'renting a similar place would cost less each month'}${d.rent ? `. Net rental yield after costs: ${pct(d.rent.netYield)}.` : '.'}</p>`
    : '<p>Compare this with the going rent for a similar house nearby. If it is well below this figure, you are paying a premium to own. Add <code>--rent</code> to test it.</p>';
  const cur = (dep: number, i: number) => dep === p.depositPct && i === 1 ? ' class="cur"' : '';
  const grid = `<table class="g"><tr><td></td>${[-1, 0, 1, 2].map(r => `<td class="r"><b>${(p.rate + r).toFixed(2)}%</b></td>`).join('')}</tr>${d.grid.map(g => `<tr><td><b>${g.dep}% deposit</b></td>${g.cells.map((c, i) => `<td class="r"${cur(g.dep, i)}>${R(c)}</td>`).join('')}</tr>`).join('')}</table>`;
  const facts: [string, string, string][] = [['Type', L.propertyType ?? '', 'propertyType'], ['Title', L.titleType === 'unknown' ? '' : L.titleType, 'titleType'], ['Bedrooms', String(L.beds ?? ''), 'beds'], ['Bathrooms', String(L.baths ?? ''), 'baths'], ['Parking', String(L.parking ?? ''), 'parking'], ['Floor size', L.floorSqm ? L.floorSqm + ' m²' : '', 'floorSqm'], ['Erf size', L.erfSqm ? L.erfSqm + ' m²' : '', 'erfSqm'], ['Rates', L.rates ? R(L.rates) + ' a month' : '', 'rates'], ['Levy', L.levy ? R(L.levy) + ' a month' : '', 'levy'], ['Features', L.features.join(', '), 'features']];
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Buyer decision report: ${esc(L.title ?? L.url)}</title><style>
:root{--bg:#f3f5f7;--card:#fff;--ink:#141b22;--mute:#5a6673;--line:#e3e8ec;--acc:#1f6f78;--good:#17603c;--warn:#8f5a00;--bad:#b42318}
@media(prefers-color-scheme:dark){:root{--bg:#0e1419;--card:#172028;--ink:#e9eef2;--mute:#9aa8b4;--line:#27333d;--acc:#79c2cc;--good:#5fd39a;--warn:#f0b04a;--bad:#ff8b7e}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.6 Inter,system-ui,-apple-system,"Segoe UI",sans-serif}main{max-width:820px;margin:0 auto;padding:24px 16px 60px}
section{background:var(--card);border-radius:24px;padding:28px;margin:18px 0;box-shadow:0 1px 3px rgba(0,0,0,.06)}.hero{padding:0;overflow:hidden}.hero img{width:100%;max-height:360px;object-fit:cover;display:block}.hero div.in{padding:28px}
.eye{font-size:12px;letter-spacing:.12em;text-transform:uppercase;color:var(--acc);font-weight:600}h1{font-size:38px;line-height:1.1;letter-spacing:-.03em;font-weight:800;margin:10px 0}h2{font-size:28px;line-height:1.2;letter-spacing:-.02em;font-weight:800;margin:6px 0 16px}
.price{font-size:34px;font-weight:800;letter-spacing:-.02em}.tiles{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px;margin:14px 0}.tile{border:1px solid var(--line);border-radius:16px;padding:16px}.tile .eye{color:var(--mute)}.tile .v{font-size:22px;font-weight:700;letter-spacing:-.01em;margin:4px 0}.tile p{margin:0;font-size:14px;color:var(--mute)}
.verdict{border-left:8px solid var(--${tone})}.verdict .s{font-size:30px;font-weight:800;color:var(--${tone})}.mute,small{color:var(--mute)}.miss{color:var(--warn)}
table{width:100%;border-collapse:collapse}td{padding:9px 6px;border-bottom:1px solid var(--line)}td.r{text-align:right}.g td.cur{background:color-mix(in srgb,var(--acc) 16%,transparent);font-weight:700}.wrap{overflow-x:auto}
ol,ul{padding-left:22px}li{margin:8px 0}.h{color:var(--bad);font-weight:700}.m{color:var(--warn);font-weight:700}.bar{height:8px;background:var(--line);border-radius:4px;overflow:hidden}.bar i{display:block;height:100%;background:var(--acc);width:${d.readiness}%}a{color:var(--acc)}code{background:var(--line);padding:1px 5px;border-radius:5px}
@media(max-width:560px){h1{font-size:30px}section{padding:20px}}</style></head><body><main>
<section class="hero">${L.image ? `<img src="${esc(L.image)}" alt="">` : ''}<div class="in"><div class="eye">Buyer decision report</div><h1>${esc(L.title ?? 'Property')}</h1><div class="mute">${esc(L.suburb ?? '')} · <a href="${esc(L.url)}">Listing</a></div>
<div class="eye" style="margin-top:18px">Asking price</div><div class="price">${R(d.price)}</div>
${tiles([tile('Bedrooms', String(L.beds ?? '?')), tile('Bathrooms', String(L.baths ?? '?')), tile('Floor', L.floorSqm ? L.floorSqm + ' m²' : 'Not stated'), tile('Erf', L.erfSqm ? L.erfSqm + ' m²' : 'Not stated')])}</div></section>
<section class="verdict"><div class="eye">The verdict</div><div class="s">${d.status}</div><p>${d.summary}</p><h2 style="font-size:20px">Do these before you make an offer</h2><ol>${d.plan.map(x => `<li>${esc(x)}</li>`).join('')}</ol>
<small>Decision readiness ${d.readiness}/100: how much of the evidence needed for an offer is in hand.</small><div class="bar"><i></i></div></section>
${card('What it costs each month', `${R(d.monthly)} a month, all in.`, tiles([tile('Bond', R(d.bond), `${p.depositPct}% deposit, ${p.rate}%, ${p.termYears} years`), tile('Rates and levy', R((L.rates ?? 0) + (L.levy ?? 0)), L.levy ? '' : L.titleType === 'freehold' ? 'No levy (freehold)' : 'Levy not stated'), tile('Upkeep reserve', R(d.reserve), '1% of value a year'), tile('Income needed', R(d.incomeNeeded), 'gross a month at 30% of income')]) + `<p class="mute">Utilities, insurance and security are extra.</p>`)}
${card('Cash to close', `${R(d.upfront)} before you can move in.`, tiles([tile('Deposit', R(d.deposit)), tile('Transfer duty', p.vatSale ? 'R 0' : R(d.duty), p.vatSale ? 'VAT sale' : 'SARS 2026/27 table'), tile('Legal and bond fees', R(d.fees), 'Estimate at 3%. Get a quote.')]))}
${card('Stress test', `If rates rise 2 points, the bond is ${R(d.grid[1].cells[3])}.`, `<div class="wrap">${grid}</div><p class="mute">Monthly bond by deposit and interest rate. The highlighted cell is your scenario. A bigger deposit lowers the bond and the rate risk.</p>`)}
${card('Is the price fair?', b ? `Asking is ${pct(Math.abs(b.gap))} ${b.position === 'in line' ? 'from the benchmark' : b.position} the benchmark.` : 'Not proven yet. Here is what we can check.',
    tiles([tile('Asking', R(d.price)), tile('Comparable benchmark', b ? R(b.value) : 'Needs sales', b ? `${b.n} sales, ${b.strength} evidence` : 'Add 3+ sales with --comps'), tile('City value implied by rates', d.implied ? `${R(d.implied.low)} to ${R(d.implied.high)}` : 'Cape Town only', d.implied ? 'Municipal, not market value' : 'Use --city ct'), tile('Price per m² of floor', d.perFloor ? R(d.perFloor) : 'Needs floor size')])
    + (b?.position === 'above' ? `<p>A reasoned opening range to discuss: ${R(b.low)} to ${R(b.value)}.</p>` : '')
    + (d.ct ? `<p class="mute">Context: Stats SA's house price index for the City of Cape Town rose 11.4% in the year to February 2026. That is a metro average and says nothing about this street.</p>` : ''))}
${card('Buy or rent, and how long to stay', `Owning costs ${R(d.ownCost)} a month before principal.`, `<p>That is the bond interest plus rates, levy and upkeep. About ${R(d.principal1)} of your first instalment repays the loan, which builds equity rather than being a cost.</p>${rentLine}
<p>Buying and selling costs mean the price must rise about <b>${pct(d.uplift)}</b> before you get back what you spent. Years needed at different growth rates:</p>
<table>${d.breakEven.map(x => `<tr><td>${x.g}% a year</td><td class="r">${x.years.toFixed(1)} years</td></tr>`).join('')}</table><p class="mute">Assumes about 6% selling costs. Growth is not guaranteed.</p>`)}
${card('Watch-outs', 'Check these before you commit.', `<ul>${d.flags.map(f => `<li><span class="${f.level === 'high' ? 'h' : f.level === 'medium' ? 'm' : 'mute'}">${f.level === 'high' ? 'Important' : f.level === 'medium' ? 'Check' : 'Note'}:</span> ${esc(f.text)}</li>`).join('')}</ul>`)}
${card('How to structure your offer', 'Protect yourself in the offer to purchase.', `<p>Ask your conveyancer to include these conditions, so you can withdraw without penalty if they fail:</p><ul><li>Bond approval within a fixed number of days</li><li>A satisfactory building inspection (roof, damp, wiring, plumbing, timber pests)</li><li>Seller provides valid electrical, plumbing and beetle certificates, plus the electric fence and gas certificates if applicable</li><li>Approved building plans for all structures</li><li>A clear list of what stays (fittings, appliances, solar) and the occupation date</li></ul>`)}
${card('Ask the agent', 'Questions that change the price.', `<ul>${d.questions.map(q => `<li>${esc(q)}</li>`).join('')}</ul>`)}
${card('What we found', 'The listing facts and where they came from.', `<table>${facts.map(([l, v, k]) => `<tr><td>${l}</td><td class="r">${na(v, x => esc(x) + ` <small>${src[L.src[k]] ?? 'from listing'}</small>`)}</td></tr>`).join('')}</table><p class="mute">Not found means the listing did not state it. Nothing is assumed.</p>`)}
<section><div class="eye">Method and limits</div><p class="mute">Decision support only. It is not a valuation, or financial, tax or legal advice. Transfer duty uses the SARS table effective 1 April 2025 and unchanged for 2026/27. Bond figures use the rate you entered (prime was 10.5% at last check) and a bank quote will differ. Legal fees, 1% upkeep, 6% selling costs and the 30% income rule are guidelines. The municipal value estimate brackets the 2025/26 and 2026/27 Cape Town rates tariffs because published figures differ, and the rates on the listing may be out of date. Verify every figure before you sign.</p></section>
</main></body></html>`;
}
